Implemented json-api-builder
distributed-lab/web-kit-old pull request #13
Opened 2022-11-28 10:01 UTC by yehor-podporinov

2022-11-29 08:20 UTC, napalmpapalam requested changes

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiRelationship = {
relationship object has different type, 4 example if u have account as relation it will looks like:
```json
{
  "data": {
   ...
       "relationships": {
       "account": {
         data: {
           "id": "1",
           "type": "accounts"
         }
        }
   }
   },
}
```


so u can know which type it will be because the keys names is dynamic, but value should be the same  -JsonApiRecordBase 

```ts
export type JsonApiRelationship<T extends string> = Record<
  string,
  JsonApiRecordBase<T>
>

export type JsonApiRelationships<T extends string = ''> = Record<
  string,
  JsonApiRelationship<T>
>
```

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostBody = {
it should be named as `JsonApiRecord`

```ts
export type JsonApiRecordData = {
  data: JsonApiPostResource
  included?: []JsonApiRecordData
} & JsonApiLinks
```

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostResource = {
```ts
export type JsonApiRecordData<T extends string = ''> = JsonApiRecordBase<T> & JsonApiLinks & {
   attributes?: JsonApiRecordAttributes
   relationships?: JsonApiRelationships
}
```

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +  Record<string, unknown>
remove

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +  links?: JsonApiLinks
left only one `JsonApiLinks` type: 

```ts
export type JsonApiLinks = {
  links?: { [key in JsonApiLinkFields]?: Endpoint }
}
```

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +  jsonapi?: JsonApiImplementation
remove this fields and types we don't need it

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostRelationships = Record<
remove

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostRelationship = {
remove

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +}
remove, replace with existing types

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +}
remove

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiResource = {
remove, it's `JsonApiRecordData`

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +}
remove

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiMeta = Record<string | number | symbol, unknown>
remove

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiAttributes = Record<string | number | symbol, unknown>
```ts
export type JsonApiAttributes = Record<string, unknown>
```

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  }
remove

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setDataType(type: string) {
`setType`

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setData(resource: JsonApiPostResource) {
1. add public to all methods
2. all public methods should have described return type not dynamically generated

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setDataID(id: string) {
`setID`

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setDataAttributes(attributes: JsonApiAttributes) {
`setAttributes`

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setDataRelationships(relationships: JsonApiPostRelationships) {
setRelationships

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setIncluded(included: JsonApiPostResource[]) {
params should be - `(included: InstanceType<typeof JsonApiPostBodyBuilder>[])`

then in build method u just mapping it and execute build method

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  }
remove

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  }
remove

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  }
remove

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +}
u dont have to reset builder

2022-11-29 08:20 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +import {
1. create index.ts in this directory and export this class from it, after it export all utils from src/index.ts, otherwise it not importable
2. increment version in `package.json`, and add changes to `CHANGELOG.md` according to [semver](https://semver.org/)
3. add test coverage

2022-11-29 10:14 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostBody = {
Query body as `record`? `Body` is a more abstract name

2022-11-29 10:58 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiRelationship = {
What if different relationships have different types in the relationships object?

2022-11-29 12:03 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiRelationship = {
If according to specification then JsonApiRecordBase haven't all properties that describred there.

2022-11-29 12:17 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostBody = {
I've renamed this to `JsonApiPostRecord`

2022-11-29 12:45 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostResource = {
In your name example, prefix `Post` is not exists
=> It is not immediately clear whether this is a record of the getted object or the object that will be created

2022-11-29 12:56 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +  Record<string, unknown>
I added object with properties data and meta, according to specification, but this line created before me and I'd not remove this line to so that something doesn't go wrong

2022-11-29 13:00 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +  links?: JsonApiLinks
!

2022-11-29 13:04 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostRelationships = Record<
`JsonApiPostRelationships` and `JsonApiRelationships` differ in that in first of them the data field is required

2022-11-29 13:04 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostRelationship = {
!

2022-11-29 13:29 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostBody = {
Done

2022-11-29 13:30 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostResource = {
Done

2022-11-29 13:30 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +  Record<string, unknown>
Done

2022-11-29 13:33 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +  links?: JsonApiLinks
Done

2022-11-29 13:40 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +  jsonapi?: JsonApiImplementation
Done

2022-11-29 13:41 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostRelationships = Record<
Done

2022-11-29 13:41 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiPostRelationship = {
Done

2022-11-29 13:42 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +}
+-

2022-11-29 13:42 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +}
Done

2022-11-29 13:42 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiResource = {
Done

2022-11-29 13:43 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +}
Done

2022-11-29 13:44 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiMeta = Record<string | number | symbol, unknown>
Done

2022-11-29 13:44 UTC, yehor-podporinov commented on packages/json-api-client/src/types/json-api.ts
> +export type JsonApiAttributes = Record<string | number | symbol, unknown>
Done

2022-11-29 13:47 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setData(resource: JsonApiPostResource) {
1. +
2. -

2022-11-29 13:49 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setIncluded(included: JsonApiPostResource[]) {
-

2022-11-29 14:02 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  }
Done

2022-11-29 14:02 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setDataType(type: string) {
Done

2022-11-29 14:03 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setDataID(id: string) {
Done

2022-11-29 14:03 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setDataAttributes(attributes: JsonApiAttributes) {
Done

2022-11-29 14:04 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setDataRelationships(relationships: JsonApiPostRelationships) {
Done

2022-11-29 14:11 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +}
Done

2022-11-29 14:11 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  }
Done

2022-11-29 14:11 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  }
Done

2022-11-29 14:11 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  }
Done

2022-11-29 14:37 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +  setIncluded(included: JsonApiPostResource[]) {
Done

2022-11-29 15:00 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +import {
Version 2.0.5?

2022-11-29 15:50 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +import {
sorry, in readme of json api client

2022-11-29 15:52 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +import {
it should be minor version

2022-11-29 15:53 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-post-body-builder.ts
> +import {
https://semver.org/#spec-item-7

> It MAY be incremented if substantial new functionality or improvements are introduced within the private code.

2022-11-30 14:36 UTC, napalmpapalam requested changes

2022-11-30 14:36 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-body-builder.ts
> +  private body: JsonApiRecord
name private fields with `_` prefix, it's JS community convention

2022-11-30 14:36 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-body-builder.ts
> +  public setData(data: JsonApiRecordData): JsonApiBodyBuilder {
`public setData<T = string>(data: JsonApiRecordData<T>): JsonApiBodyBuilder {`

2022-11-30 14:36 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-body-builder.ts
> +  public setData(data: JsonApiRecordData): JsonApiBodyBuilder {
generic should be optional so check it

2022-11-30 14:36 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-body-builder.ts
> +  public setData(data: JsonApiRecordData): JsonApiBodyBuilder {
and add in every method which argument can  accept generic type

2022-11-30 14:36 UTC, napalmpapalam commented on packages/json-api-client/src/utils/json-api-body-builder.test.ts
> +
wrap all describe test cases in one describe with message like: `performs JsonApiBodyBuilder unit test`

2022-11-30 14:49 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-body-builder.ts
> +  private body: JsonApiRecord
maybe #?

2022-11-30 15:17 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-body-builder.ts
> +  private body: JsonApiRecord
Done

2022-11-30 15:18 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-body-builder.test.ts
> +
Done

2022-11-30 15:32 UTC, yehor-podporinov commented on packages/json-api-client/src/utils/json-api-body-builder.ts
> +  public setData(data: JsonApiRecordData): JsonApiBodyBuilder {
Done

2022-12-01 09:19 UTC, napalmpapalam approved these changes

2022-12-01 09:20 UTC, merged