feature/date.js-extension
distributed-lab/web-kit-old pull request #15
Opened 2022-11-30 22:00 UTC by yehor-podporinov

2022-12-01 10:05 UTC, ArtSuslov requested changes

2022-12-01 10:05 UTC, ArtSuslov commented on packages/utils/src/date.ts
> +import calendar from 'dayjs/plugin/calendar'
import { calendar, isSameOrAfter, isSameOrBefore  } from 'dayjs/plugin'

2022-12-01 10:05 UTC, ArtSuslov commented on packages/utils/src/date.ts
> +    return 'YYYY-MM-DDT00:00:00+00:00'
are u sure there shouldn't be a trailing 'Z'  to show the time-zone?

2022-12-01 10:11 UTC, yehor-podporinov commented on packages/utils/src/date.ts
> +import calendar from 'dayjs/plugin/calendar'
It's not working

2022-12-07 14:30 UTC, yehor-podporinov commented on packages/utils/src/date.ts
> +    return 'YYYY-MM-DDT00:00:00+00:00'
I've removed this getter, because it not used in web client in tokend

2022-12-08 10:35 UTC, ArtSuslov requested changes

2022-12-08 10:35 UTC, ArtSuslov commented on packages/utils/README.md
> +<details><summary>1.2.0</summary>
1.2.0 -> Unreleased

2022-12-08 10:35 UTC, ArtSuslov commented on packages/utils/package.json
> +  "version": "1.2.0",
1.1.0

2022-12-08 10:45 UTC, yehor-podporinov commented on packages/utils/README.md
> +<details><summary>1.2.0</summary>
Done

2022-12-08 10:45 UTC, yehor-podporinov commented on packages/utils/package.json
> +  "version": "1.2.0",
Done

2022-12-23 14:58 UTC, napalmpapalam requested changes

2022-12-23 14:58 UTC, napalmpapalam commented on packages/utils/src/date.ts
> +})
create method in DateUtils to update locales outside of the package

2023-01-17 11:18 UTC, napalmpapalam requested changes

2023-01-17 11:18 UTC, napalmpapalam commented on packages/utils/src/time.ts
> +import duration, { Duration } from 'dayjs/plugin/duration'
create own one Duration type

2023-01-17 11:18 UTC, napalmpapalam commented on packages/utils/src/time.ts
> +    return this.#date.utc(true).format('YYYY-MM-DDTHH:mm:ss') + 'Z'
```ts
format('YYYY-MM-DDTHH:mm:ss[Z]')
```

2023-01-17 11:18 UTC, napalmpapalam commented on packages/utils/src/time.ts
> +  public static updateLocale(
`setLocale`

2023-01-17 11:18 UTC, napalmpapalam commented on packages/utils/src/time.ts
> +  public static locale(
do u tested it?

2023-01-17 11:18 UTC, napalmpapalam commented on packages/utils/src/time.ts
> +export class TimeDuration {
rename to `Duration`, why it's not in the separated file?

2023-01-17 11:18 UTC, napalmpapalam commented on packages/utils/src/time.ts
> +  }
add more common methods

2023-01-17 11:18 UTC, napalmpapalam commented on packages/utils/src/types/time.ts
> +// }>
?????????/

2023-01-17 11:20 UTC, napalmpapalam commented on packages/utils/src/date.ts
> +    return 'YYYY-MM-DDT00:00:00+00:00'
it doesn't matter, not only tokend uses this package

2023-01-17 11:22 UTC, napalmpapalam requested changes

2023-01-17 11:22 UTC, napalmpapalam commented on packages/utils/README.md
> +    <h5>New getters to Time</h5>
if u add something it's obvious that it's new

2023-01-27 07:16 UTC, napalmpapalam requested changes

2023-01-27 07:16 UTC, napalmpapalam commented on packages/utils/src/duration.ts
> +  public humanize(): string {
make all methods as getters

2023-01-27 07:16 UTC, napalmpapalam commented on packages/utils/src/duration.ts
> +export const timeDuration = (units: TimeDurationUnitsObject): TimeDuration =>
`duration`

2023-01-27 07:16 UTC, napalmpapalam commented on packages/utils/src/duration.ts
> +  public asMilliseconds(): UnixDate {
return type is number, not `UnixDate`, unix date is timestamp

2023-01-27 07:16 UTC, napalmpapalam commented on packages/utils/src/time.ts
> +export class TimeDuration {
class not renamed

2023-01-27 07:59 UTC, napalmpapalam approved these changes

2023-01-27 08:00 UTC, merged