adding-utils-and-json-api-packages
distributed-lab/web-kit-old pull request #3
Opened 2022-09-01 10:09 UTC by Sorizen

2022-09-01 10:40 UTC, napalmpapalam requested changes

2022-09-01 10:40 UTC, napalmpapalam commented on .gitignore
> -yarn-error.log*
why did u remove it?

2022-09-01 10:40 UTC, napalmpapalam commented on jest.config.base.js
> +    "^lodash-es$": "lodash"
this possibly can be removed, you shouldn't use `lodash-es`, it wouldn't compile into CommonJS, so try to remove it or rename it to `lodash` if you resolve some errors

2022-09-01 10:40 UTC, napalmpapalam commented on packages/utils/README.md
> +# @dl/json-api-client
it's not json-api-client

2022-09-01 10:40 UTC, napalmpapalam commented on packages/utils/src/browser.ts
> +  ;(window as any).webKitUtils = utils
?

2022-09-01 10:40 UTC, napalmpapalam commented on packages/utils/src/date.ts
> +type UnixDate = number
move to `types/date.ts`

2022-09-01 10:40 UTC, napalmpapalam commented on packages/utils/src/math.ts
> +    ROUND_TYPE = ROUNDING_MODES.ROUND_UP,
try to omit casting type with `as` in `BigNumber.config()`:

```ts
type RoundingMode = BigNumber.RoundingMode

static subtract(
...
ROUND_TYPE: RoundingMode  = ROUNDING_MODES.ROUND_UP
...
)
```

2022-09-01 10:40 UTC, napalmpapalam commented on packages/utils/src/math.ts
> +  static get roundingModes(): typeof ROUNDING_MODES {
use created type `RoundingModes`, as I wrote upwards

2022-09-01 10:40 UTC, napalmpapalam commented on packages/utils/tsconfig.json
>        "ES6",
Change log

2022-09-02 07:03 UTC, Sorizen commented on .gitignore
> -yarn-error.log*
returned

2022-09-02 07:10 UTC, Sorizen commented on jest.config.base.js
> +    "^lodash-es$": "lodash"
removed

2022-09-02 07:11 UTC, Sorizen commented on packages/utils/README.md
> +# @dl/json-api-client
returned

2022-09-02 07:11 UTC, Sorizen commented on packages/utils/src/browser.ts
> +  ;(window as any).webKitUtils = utils
returned

2022-09-02 08:07 UTC, Sorizen commented on packages/utils/src/math.ts
> +    ROUND_TYPE = ROUNDING_MODES.ROUND_UP,
done

2022-09-02 08:07 UTC, Sorizen commented on packages/utils/src/math.ts
> +  static get roundingModes(): typeof ROUNDING_MODES {
done

2022-09-02 08:14 UTC, Sorizen commented on packages/utils/src/date.ts
> +type UnixDate = number
done

2022-09-02 09:16 UTC, napalmpapalam requested changes

2022-09-02 09:16 UTC, napalmpapalam commented on packages/utils/types/date.ts
> +export type IsoDate = string // RFC3999Nano ISO Date String
u should export it from `index.ts` from the current directory and then export it from `src/index.ts`, thus client-code be able to import type from the lib

2022-09-02 09:16 UTC, napalmpapalam commented on packages/utils/CHANGELOG.md
> +### Fixed
u don't have to add all `###*` if u don't have changes for it, just to 

```md
##[Unreleased]
### Under the hood changes
- Initiated project with basic utilities
```

2022-09-02 09:22 UTC, Sorizen commented on packages/utils/types/date.ts
> +export type IsoDate = string // RFC3999Nano ISO Date String
done

2022-09-02 09:22 UTC, Sorizen commented on packages/utils/CHANGELOG.md
> +### Fixed
done

2022-09-13 07:28 UTC, napalmpapalam requested changes

2022-09-13 07:28 UTC, napalmpapalam commented on jest.config.base.js
> +  },
are u sure that this cannot be populated from base config or at least any of these fields?

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/CHANGELOG.md
> +##[Unreleased]
let's initiate packages, for now, with `1.0.0` version, also add do the same for `@dl/utils`

```markdown
## [1.0.0] - 2022-09-13
### Under the hood changes
- Initiated project with basic functionality
...
```

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/package.json
> +    "displayName": "@dl/utils"
wtf?

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/package.json
> +    "@types/lodash": "^4.14.184",
this should be in `devDependencies` section

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/const/client.const.ts
> +} as const
1. u don't need this
2. I said don't push unrelated stuff to Github

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/enums/application.ts
> +}
how it's related with json api http client

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/enums/client.ts
> +}
how it's related with json api http client

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/enums/data.ts
> +}
how it's related with json api http client

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/enums/http.ts
> +}
https://www.npmjs.com/package/http-status

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/enums/http.ts
> +}
https://www.npmjs.com/package/http-methods-constants

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/enums/identity.ts
> +export enum IDENTITY_STATES {
how it's related with json api http client

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/enums/network.ts
> +}
how it's related with json api http client

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/enums/transaction.ts
> +  failed = 'failed',
how it's related with json api http client

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/helpers/type-checks.ts
> +export const isMetaSellOrderArray = (
how it's related with json api http client

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/response.ts
> +    if (raw.status === 204 || raw.status === 205) {
use constants

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/response.ts
> +      }
```js
     intersection += char
     if (baseUrl.endsWith(intersection + char)) break
```

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/types/callers.ts
> +import {
this file should be deleted

2022-09-13 07:28 UTC, napalmpapalam commented on packages/json-api-client/src/types/client.ts
> +import {
this file should be deleted

2022-09-13 07:29 UTC, napalmpapalam requested changes

2022-09-13 07:29 UTC, napalmpapalam commented on packages/json-api-client/src/browser.ts
> +console.warn('Web Kit Utils was added to the window object.')
????

2022-09-20 10:33 UTC, Sorizen commented on packages/json-api-client/package.json
> +    "displayName": "@dl/utils"
done

2022-09-20 10:34 UTC, Sorizen commented on packages/json-api-client/package.json
> +    "@types/lodash": "^4.14.184",
done

2022-09-20 10:35 UTC, Sorizen commented on packages/json-api-client/src/const/client.const.ts
> +} as const
done

2022-09-20 10:37 UTC, Sorizen commented on packages/json-api-client/src/enums/application.ts
> +}
done

2022-09-20 10:38 UTC, Sorizen commented on packages/json-api-client/src/enums/client.ts
> +}
done

2022-09-20 10:40 UTC, Sorizen commented on packages/json-api-client/src/enums/data.ts
> +}
done

2022-09-20 10:44 UTC, Sorizen commented on packages/json-api-client/src/enums/identity.ts
> +export enum IDENTITY_STATES {
done

2022-09-20 10:45 UTC, Sorizen commented on packages/json-api-client/src/enums/network.ts
> +}
done

2022-09-20 10:46 UTC, Sorizen commented on packages/json-api-client/src/enums/transaction.ts
> +  failed = 'failed',
done

2022-09-20 10:46 UTC, Sorizen commented on packages/json-api-client/src/helpers/type-checks.ts
> +export const isMetaSellOrderArray = (
done

2022-09-20 10:47 UTC, Sorizen commented on packages/json-api-client/src/response.ts
> +      }
done

2022-09-20 10:48 UTC, Sorizen commented on packages/json-api-client/src/types/callers.ts
> +import {
done

2022-09-20 10:49 UTC, Sorizen commented on packages/json-api-client/src/types/client.ts
> +import {
done

2022-09-20 10:49 UTC, Sorizen commented on packages/json-api-client/src/browser.ts
> +console.warn('Web Kit Utils was added to the window object.')
done

2022-09-20 10:58 UTC, Sorizen commented on packages/json-api-client/src/response.ts
> +    if (raw.status === 204 || raw.status === 205) {
done

2022-09-20 14:38 UTC, Sorizen commented on packages/json-api-client/src/enums/http.ts
> +}
done

2022-09-20 14:38 UTC, Sorizen commented on packages/json-api-client/src/enums/http.ts
> +}
done

2022-09-20 14:38 UTC, Sorizen commented on jest.config.base.js
> +  },
done

2022-09-20 14:40 UTC, Sorizen commented on packages/json-api-client/CHANGELOG.md
> +##[Unreleased]
done

2022-09-22 07:21 UTC, napalmpapalam requested changes

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/package.json
> +  "browser": "./lib/utils.min.js",
why a u doing this ?

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/browser.ts
> +console.warn('Web Kit Utils was added to the window object.')
what is done? there are still "Utils" in the log

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/json-api.ts
> +   * Rarify manages authentication and ownership within its system via bearer
remove rarify mention

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/json-api.ts
> +   * All endpoints in the Rarify API use bearer authToken authentication.
.

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +            "id": "rarinet"
remove rarify mention

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +    "email": "loktionov.kh@gmail.com",
replace with foo@bar.com

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +          "image_url": "https://rarify-user-content-dev.s3.amazonaws.com/2b3a17df-932d-4421-b03c-b05cebc7eae5",
`https://my-fake-url.com/2b3a17df-932d-4421-b03c-b05cebc7eae`

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +    "email": "loktionov.semen.kh@gmail.com",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +          "image_url": "https://rarify-user-content-dev.s3.amazonaws.com/2b3a17df-932d-4421-b03c-b05cebc7eae5",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +    "email": "loktionov.semen.kh@gmail.com",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +          "image_url": "https://rarify-user-content-dev.s3.amazonaws.com/2b3a17df-932d-4421-b03c-b05cebc7eae5",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +        "email": "loktionov.kh@gmail.com",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +        "email": "loktionov.semen.kh@gmail.com",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +        "email": "loktionov.semen.kh@gmail.com",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +            "id": "rarinet",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +        "image_url": "https://rarify-user-content-dev.s3.amazonaws.com/2b3a17df-932d-4421-b03c-b05cebc7eae5",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +            "id": "rarinet",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-without-links-raw.json
> +        "email": "loktionov.kh@gmail.com",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-without-links-raw.json
> +        "email": "loktionov.semen.kh@gmail.com",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-without-links-raw.json
> +        "email": "loktionov.semen.kh@gmail.com",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/test/mocks/json-api-response-without-links-raw.json
> +        "image_url": "https://rarify-user-content-dev.s3.amazonaws.com/2b3a17df-932d-4421-b03c-b05cebc7eae5",
/

2022-09-22 07:21 UTC, napalmpapalam commented on packages/json-api-client/src/types/json-api.ts
> +export type RequestOpts = {
not consistent type naming => `JsonApiClientRequestOpts`

2022-09-22 13:26 UTC, Sorizen commented on packages/json-api-client/src/browser.ts
> +console.warn('Web Kit Utils was added to the window object.')
100% done)

2022-09-22 13:27 UTC, Sorizen commented on packages/json-api-client/package.json
> +  "browser": "./lib/utils.min.js",
done

2022-09-22 13:29 UTC, Sorizen commented on packages/json-api-client/src/json-api.ts
> +   * All endpoints in the Rarify API use bearer authToken authentication.
done

2022-09-22 13:33 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +            "id": "rarinet"
done, changet to testnet

2022-09-22 13:34 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +    "email": "loktionov.kh@gmail.com",
done

2022-09-22 13:35 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +          "image_url": "https://rarify-user-content-dev.s3.amazonaws.com/2b3a17df-932d-4421-b03c-b05cebc7eae5",
done

2022-09-22 13:37 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +    "email": "loktionov.semen.kh@gmail.com",
changed to test@test.com

2022-09-22 13:37 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +          "image_url": "https://rarify-user-content-dev.s3.amazonaws.com/2b3a17df-932d-4421-b03c-b05cebc7eae5",
done

2022-09-22 13:37 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +    "email": "loktionov.semen.kh@gmail.com",
done

2022-09-22 13:37 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +          "image_url": "https://rarify-user-content-dev.s3.amazonaws.com/2b3a17df-932d-4421-b03c-b05cebc7eae5",
done

2022-09-22 13:37 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +        "email": "loktionov.kh@gmail.com",
done

2022-09-22 13:37 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +        "email": "loktionov.semen.kh@gmail.com",
done

2022-09-22 13:37 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +        "email": "loktionov.semen.kh@gmail.com",
done

2022-09-22 13:38 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +            "id": "rarinet",
changet to tetnet

2022-09-22 13:38 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +        "image_url": "https://rarify-user-content-dev.s3.amazonaws.com/2b3a17df-932d-4421-b03c-b05cebc7eae5",
done

2022-09-22 13:38 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-raw.json
> +            "id": "rarinet",
done

2022-09-22 13:38 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-without-links-raw.json
> +        "email": "loktionov.kh@gmail.com",
done

2022-09-22 13:38 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-without-links-raw.json
> +        "email": "loktionov.semen.kh@gmail.com",
done

2022-09-22 13:38 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-without-links-raw.json
> +        "email": "loktionov.semen.kh@gmail.com",
done

2022-09-22 13:38 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-without-links-raw.json
> +        "image_url": "https://rarify-user-content-dev.s3.amazonaws.com/2b3a17df-932d-4421-b03c-b05cebc7eae5",
done

2022-09-22 13:43 UTC, Sorizen commented on packages/json-api-client/src/test/mocks/json-api-response-parsed.json
> +    "email": "loktionov.kh@gmail.com",
changed to test@test.com

2022-09-22 13:51 UTC, Sorizen commented on packages/json-api-client/src/types/json-api.ts
> +export type RequestOpts = {
done

2022-09-23 08:09 UTC, napalmpapalam approved these changes

2022-09-23 08:14 UTC, merged